# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-17 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxfNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
                ('name', models.CharField(max_length=100, verbose_name='文字信息')),
            ],
            options={
                'db_table': 'axf_nav',
            },
        ),
        migrations.CreateModel(
            name='AxfShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
                ('name', models.CharField(max_length=100, verbose_name='文字信息')),
            ],
            options={
                'db_table': 'axf_shop',
            },
        ),
        migrations.CreateModel(
            name='AxfWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
                ('name', models.CharField(max_length=100, verbose_name='文字信息')),
            ],
            options={
                'db_table': 'axf_wheel',
            },
        ),
        migrations.CreateModel(
            name='MustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
                ('name', models.CharField(max_length=100, verbose_name='文字信息')),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
        ),
    ]
