# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-17 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(verbose_name='商品分类id')),
                ('typename', models.CharField(max_length=100, verbose_name='商品分类名称')),
                ('childtypenames', models.CharField(max_length=500, verbose_name='自分类的id和名称')),
                ('typesort', models.SmallIntegerField(verbose_name='排序')),
            ],
            options={
                'db_table': 'axf_foodtype',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(verbose_name='商品id')),
                ('productimg', models.CharField(max_length=100, verbose_name='商品图片')),
                ('productname', models.CharField(max_length=100, verbose_name='商品短名称')),
                ('productlongname', models.CharField(max_length=255, verbose_name='商品长名称')),
                ('specifics', models.CharField(max_length=100, verbose_name='商品规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='售价')),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='市场价')),
                ('categoryid', models.IntegerField(verbose_name='所属分类id')),
                ('childcid', models.IntegerField(verbose_name='所属自分类id')),
                ('childcidname', models.CharField(max_length=100, verbose_name='自分类名称')),
                ('storenums', models.IntegerField(verbose_name='库存')),
                ('productnum', models.IntegerField(verbose_name='销量')),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
